packages:
  - apps/*
  - packages/*
  - tools/*

catalog:
  "@antfu/eslint-config": ^6.7.3
  "@antfu/ni": ^28.0.0
  "@clack/prompts": ^0.11.0
  "@discordjs/rest": ^2.6.0
  "@iconify-json/lucide": ^1.2.68
  "@iconify-json/radix-icons": ^1.2.5
  "@internationalized/date": ^3.10.0
  "@libsql/darwin-arm64": ^0.5.22
  "@libsql/darwin-x64": ^0.5.22
  "@libsql/linux-x64-musl": ^0.5.22
  "@libsql/linux-x64-gnu": ^0.5.22
  "@libsql/linux-arm64-gnu": ^0.5.22
  "@libsql/linux-arm64-musl": ^0.5.22
  "@libsql/win32-x64": ^0.5.22
  "@number-flow/vue": ^0.4.9
  "@nuxt/eslint": ^1.9.0
  "@nuxt/icon": ^1.15.0
  "@nuxt/ui": ^4.4.0
  "@nuxtjs/color-mode": ^3.5.2
  "@orpc/client": ^1.13.4
  "@orpc/contract": ^1.13.4
  "@orpc/openapi": ^1.13.4
  "@orpc/openapi-client": ^1.13.4
  "@orpc/server": ^1.13.4
  "@orpc/valibot": ^1.13.4
  "@pinia/nuxt": ^0.5.5
  "@tailwindcss/vite": ^4.1.14
  "@tanstack/vue-table": ^8.21.3
  "@tauri-apps/cli": ^2.9.6
  "@types/atomic-sleep": ^1.0.1
  "@types/luxon": ^3.7.1
  "@types/node": ^25.1.0
  "@unovis/ts": ^1.6.1
  "@unovis/vue": ^1.6.1
  "@vitest/coverage-v8": ^3.2.4
  "@vueuse/core": ^12.8.2
  "@vueuse/math": ^12.8.2
  "@vueuse/motion": ^3.0.3
  "@vueuse/nuxt": ^12.8.2
  atomic-sleep: ^1.0.0
  better-auth: ^1.4.10
  better-sqlite3: ^12.5.0
  class-variance-authority: ^0.7.1
  clsx: ^2.1.1
  date-fns: ^4.1.0
  discord.js: ^14.22.1
  discord.js-rate-limiter: 1.3.2
  drizzle-kit: ^0.31.8
  drizzle-orm: ^0.45.1
  drizzle-valibot: ^0.4.2
  embla-carousel: ^8.6.0
  embla-carousel-vue: ^8.6.0
  eslint: ^9.39.2
  eslint-plugin-format: ^1.3.1
  lucide-vue-next: ^0.482.0
  ms: 3.0.0-canary.202508261828
  nanoid: ^5.1.6
  nodemon: ^3.1.7
  on-exit-leak-free: ^2.1.2
  reka-ui: ^2.5.1
  release-it: ^19.0.5
  shadcn-nuxt: 2.3.1
  simple-git-hooks: ^2.13.1
  sonic-boom: ^4.2.0
  tailwind-merge: ^2.6.0
  tailwindcss: ^4.1.18
  tailwindcss-animate: ^1.0.7
  thread-stream: ^4.0.0
  tsdown: ^0.20.1
  turbo: ^2.3.3
  tw-animate-css: ^1.4.0
  typescript: ^5.9.3
  valibot: ^1.2.0
  vaul-vue: ^0.4.1
  vite: ^7.3.0
  vitest: ^3.2.4
  vitest-mock-extended: ^3.1.0
  vue: ^3.5.22
  vue-router: ^4.5.1
  vue-sonner: ^2.0.9
  vue-tsc: ^2.2.12
  vuedraggable: ^4.1.0
  yaml: ^2.8.2
  zod: ^4.3.4

ignoredBuiltDependencies:
  - "@tailwindcss/oxide"
  - esbuild

injectWorkspacePackages: true

onlyBuiltDependencies:
  - better-sqlite3
  - sharp
